"""Evaluation harness for MACVO_FrontendCov TensorRT plans.

Pipelines the polygraphy-based numerical checks plus an optional plane-nose
trajectory run, and writes a leaderboard row so multiple plans accumulate
in `runs/leaderboard.md`. Pair with Build.py to validate any new build.

Stages (each can be skipped with --skip-N):
  1. ONNX validity      - polygraphy run --validate (NaN/Inf scan).
  2. ORT-CPU reference  - cached as <onnx>.ort_outs.json on first run.
  3. TRT vs ORT parity  - mean abs / max abs / EPE diff per output.
  4. Trajectory (opt)   - macvo.exe replay + evo APE/RPE vs ground-truth TUM.
  5. Leaderboard append - one markdown row to runs/leaderboard.md.

Usage:
  # numerical parity only (no trajectory)
  python Evaluate.py --plan MACVO_FrontendCov.plan --label strongly_fast

  # full pipeline including trajectory on plane_nose
  python Evaluate.py --plan X.plan --label X \
      --macvo-exe ../MACVO_TRT/build/bin/Release/macvo.exe \
      --dataset C:/data/plane_nose \
      --gt ../MACVO_TRT/runs/plane_nose_gt_tum.txt
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import numpy as np

THIS_DIR = Path(__file__).resolve().parent


def run_cmd(cmd: list[str], desc: str) -> str:
    print(f"\n>>> {desc}", flush=True)
    print(f"    $ {' '.join(cmd)}", flush=True)
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode != 0:
        print(p.stdout, flush=True)
        print(p.stderr, file=sys.stderr, flush=True)
        raise RuntimeError(f"{desc} failed (exit {p.returncode})")
    return p.stdout


def make_loader_script(left_npy: Path, right_npy: Path, out_path: Path) -> None:
    """Generate a polygraphy data-loader script that yields a single feed_dict."""
    out_path.write_text(
        f"""# Auto-generated by Evaluate.py
import numpy as np


def load_data():
    left = np.load(r"{left_npy}").astype(np.float32)
    right = np.load(r"{right_npy}").astype(np.float32)
    if left.ndim == 3:
        left = left[None, ...]
        right = right[None, ...]
    if left.max() <= 1.5:
        left = left * 255.0
        right = right * 255.0
    yield {{
        "image_1": np.ascontiguousarray(left),
        "image_2": np.ascontiguousarray(right),
    }}
"""
    )


def stage_validate_onnx(onnx_path: Path, loader_path: Path) -> dict:
    out = run_cmd(
        [
            "polygraphy", "run", str(onnx_path),
            "--onnxrt", "--providers", "cpu",
            "--data-loader-script", str(loader_path),
            "--validate",
        ],
        desc="Stage 1: ONNX validity (NaN/Inf scan)",
    )
    return {"validate_pass": "PASSED" in out}


def stage_ort_reference(onnx_path: Path, loader_path: Path,
                        ort_outs_path: Path) -> dict:
    if ort_outs_path.exists():
        print(f"\n>>> Stage 2: ORT reference (cached at {ort_outs_path})",
              flush=True)
        return {"ort_cached": True}
    run_cmd(
        [
            "polygraphy", "run", str(onnx_path),
            "--onnxrt", "--providers", "cpu",
            "--data-loader-script", str(loader_path),
            "--save-outputs", str(ort_outs_path),
        ],
        desc="Stage 2: ORT-CPU reference (saving outputs)",
    )
    return {"ort_cached": False}


def stage_trt_parity(plan_path: Path, loader_path: Path, ort_outs_path: Path,
                     input_shape: list[int]) -> dict:
    shape_arg = f"image_1:[{','.join(map(str, input_shape))}] " \
                f"image_2:[{','.join(map(str, input_shape))}]"
    out = run_cmd(
        [
            "polygraphy", "run", str(plan_path),
            "--model-type=engine", "--trt",
            "--data-loader-script", str(loader_path),
            "--load-outputs", str(ort_outs_path),
            "--check-error-stat", "mean",
            *("--input-shapes " + shape_arg).split(),
        ],
        desc="Stage 3: TRT vs ORT tensor parity",
    )
    metrics = {}
    for line in out.splitlines():
        if "Minimum Required Tolerance" in line:
            try:
                tail = line.split("Minimum Required Tolerance")[1]
                # `mean error | [abs=0.86303] OR [rel=...]`
                abs_part = tail.split("[abs=")[1].split("]")[0]
                key = "min_atol_unknown"
                metrics[f"min_atol_{len(metrics)}"] = float(abs_part)
            except (IndexError, ValueError):
                pass
    return {"parity_lines_seen": len(metrics), **metrics}


def stage_trajectory(plan_path: Path, label: str, macvo_exe: Path,
                     dataset_dir: Path, runs_dir: Path) -> dict:
    runs_dir.mkdir(parents=True, exist_ok=True)
    tum_out = runs_dir / f"plane_nose_{label}_tum.txt"
    tum_gt_out = runs_dir / f"plane_nose_{label}_gt_tum.txt"
    run_cmd(
        [
            str(macvo_exe), "--no-viz",
            "--engine", str(plan_path),
            "--tum-output", str(tum_out),
            "--tum-gt-output", str(tum_gt_out),
            "dataset", "--dataset", str(dataset_dir),
        ],
        desc=f"Stage 4: macvo.exe trajectory ({label})",
    )
    return {"tum_run": str(tum_out), "tum_gt": str(tum_gt_out)}


def stage_evo_compare(tum_run: Path, tum_gt: Path) -> dict:
    """Compute APE + RPE via evo Python API. Same metric as scripts/compare_trajectories.py."""
    import copy
    from evo.core import metrics, sync
    from evo.core.trajectory import PoseTrajectory3D
    from evo.tools import file_interface

    ref = file_interface.read_tum_trajectory_file(str(tum_gt))
    est = file_interface.read_tum_trajectory_file(str(tum_run))
    ref_s, est_s = sync.associate_trajectories(ref, est, max_diff=0.05)
    est_aligned = copy.deepcopy(est_s)
    est_aligned.align(ref_s, correct_scale=False, correct_only_scale=False)

    ape = metrics.APE(metrics.PoseRelation.translation_part)
    ape.process_data((ref_s, est_aligned))
    rpe = metrics.RPE(metrics.PoseRelation.translation_part,
                      delta=1.0, delta_unit=metrics.Unit.frames,
                      rel_delta_tol=0.1, all_pairs=False)
    rpe.process_data((ref_s, est_aligned))
    a = ape.get_all_statistics()
    r = rpe.get_all_statistics()
    return {
        "APE_rmse": a["rmse"], "APE_mean": a["mean"], "APE_max": a["max"],
        "RPE_rmse": r["rmse"], "RPE_mean": r["mean"],
    }


def stage_leaderboard_append(runs_dir: Path, label: str, plan_path: Path,
                             metrics: dict) -> None:
    runs_dir.mkdir(parents=True, exist_ok=True)
    leaderboard = runs_dir / "leaderboard.md"
    if not leaderboard.exists():
        leaderboard.write_text(
            "| label | plan size MB | APE_rmse | APE_mean | APE_max | "
            "RPE_rmse | RPE_mean |\n"
            "|-------|-------------:|---------:|---------:|--------:|"
            "---------:|---------:|\n"
        )
    size_mb = plan_path.stat().st_size / (1024 * 1024)
    row = (
        f"| {label} | {size_mb:.1f} "
        f"| {metrics.get('APE_rmse', float('nan')):.4f} "
        f"| {metrics.get('APE_mean', float('nan')):.4f} "
        f"| {metrics.get('APE_max', float('nan')):.4f} "
        f"| {metrics.get('RPE_rmse', float('nan')):.4f} "
        f"| {metrics.get('RPE_mean', float('nan')):.4f} |\n"
    )
    with leaderboard.open("a") as f:
        f.write(row)
    print(f"\n>>> Appended leaderboard row to {leaderboard}", flush=True)
    print(row.rstrip(), flush=True)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Numerical + trajectory evaluation for MACVO TRT plans")
    p.add_argument("--plan", required=True, type=Path,
                   help="TensorRT plan to evaluate")
    p.add_argument("--label", required=True,
                   help="Short label used for run filenames + leaderboard row")
    p.add_argument("--onnx", type=Path,
                   default=THIS_DIR / "MACVO_FrontendCov.onnx",
                   help="Source ONNX (for ORT reference)")
    p.add_argument("--sample-left", type=Path,
                   help="left_t1.npy stereo sample (NCHW or CHW, [0,1] or [0,255])")
    p.add_argument("--sample-right", type=Path,
                   help="right_t1.npy stereo sample")
    p.add_argument("--input-shape", default="1,3,704,704",
                   help="Inference input shape (default: 1,3,704,704)")
    p.add_argument("--macvo-exe", type=Path,
                   help="Path to macvo.exe; if set, runs trajectory stage")
    p.add_argument("--dataset", type=Path,
                   help="Dataset directory (e.g. plane_nose); required with --macvo-exe")
    p.add_argument("--runs-dir", type=Path, default=THIS_DIR / "runs",
                   help="Where to write trajectory TUM + leaderboard")
    p.add_argument("--skip-1", action="store_true",
                   help="Skip ONNX validity stage")
    p.add_argument("--skip-2", action="store_true",
                   help="Skip ORT reference stage (assume cached)")
    p.add_argument("--skip-3", action="store_true",
                   help="Skip TRT/ORT parity stage")
    args = p.parse_args()

    input_shape = [int(x) for x in args.input_shape.split(",")]

    have_samples = args.sample_left is not None and args.sample_right is not None
    if not have_samples and not (args.skip_1 and args.skip_2 and args.skip_3):
        print("ERROR: stages 1-3 require --sample-left and --sample-right "
              "(use --skip-1 --skip-2 --skip-3 if running trajectory only)",
              file=sys.stderr)
        return 2

    metrics: dict = {}
    if have_samples:
        loader_path = args.runs_dir / "_pg_loader_auto.py"
        args.runs_dir.mkdir(parents=True, exist_ok=True)
        make_loader_script(args.sample_left, args.sample_right, loader_path)

        ort_outs_path = args.onnx.with_suffix(".ort_outs.json")
        if not args.skip_1:
            metrics.update(stage_validate_onnx(args.onnx, loader_path))
        if not args.skip_2:
            metrics.update(stage_ort_reference(args.onnx, loader_path, ort_outs_path))
        if not args.skip_3:
            metrics.update(stage_trt_parity(args.plan, loader_path,
                                            ort_outs_path, input_shape))

    if args.macvo_exe is not None:
        if args.dataset is None:
            print("ERROR: --macvo-exe requires --dataset", file=sys.stderr)
            return 2
        traj = stage_trajectory(args.plan, args.label, args.macvo_exe,
                                args.dataset, args.runs_dir)
        evo = stage_evo_compare(Path(traj["tum_run"]), Path(traj["tum_gt"]))
        metrics.update(evo)
        stage_leaderboard_append(args.runs_dir, args.label, args.plan, metrics)

    print("\n=== Final metrics ===")
    print(json.dumps(metrics, indent=2, default=str))
    return 0


if __name__ == "__main__":
    sys.exit(main())
